services:
  redis:
    image: redis:7-bookworm
    container_name: redis
    restart: always
    volumes:
      - ./data:/data
    command: redis-server --loglevel notice
    networks:
      - notebookum-network

networks:
  notebookum-network:
    external: true