services:
  consul:
    image: hashicorp/consul:1.16
    container_name: consul
    volumes:
      - "./data:/consul/data"
    command: agent -server -bootstrap-expect=1 -ui -client=0.0.0.0 -bind=0.0.0.0
    ports:
      - "8500:8500"
    networks:
      notebookum-network:
        aliases:
          - consul.universidad.localhost

networks:
  notebookum-network:
    external: true
