http:
  routers:
    traefik:
      rule: "Host(`traefik.universidad.localhost`)"
      service: "api@internal"
      entryPoints:
        - https
      tls:
        domains:
          - main: "universidad.localhost"
            sans:
              - "*.universidad.localhost"
          - main: "universidad.local"
            sans:
              - "*.universidad.local"
    notebookum:
      rule: "Host(`notebookum.universidad.localhost`)"
      service: "notebookum"
      entryPoints:
        - http
        - https

  services:
    notebookum:
      loadBalancer:
        servers:
          - url: "http://notebookum:8000"

tls:
  certificates:
    - certFile: "/etc/certs/cert.pem"
      keyFile: "/etc/certs/key.pem"
