global:
  sendAnonymousUsage: true

api:
  dashboard: true
  insecure: true

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    watch: true
    exposedByDefault: false

  file:
    filename: /etc/traefik/config.yml
    watch: true

  consulCatalog:
    endpoint:
      address: "http://consul:8500"
      token: "2be22662-4819-4a0c-81d9-b3f50c4c389c"
    exposedByDefault: false
    prefix: "traefik"
    refreshInterval: "15s"

log:
  level: DEBUG
  format: common

entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"
  postgresql:
    address: ":5432"
