global:
  sendAnonymousUsage: true

api:
  dashboard: true
  insecure: true

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    watch: true
    exposedByDefault: false

  file:
    filename: /etc/traefik/config.yml
    watch: true

  consulCatalog:
    endpoint:
      address: "http://consul:8500"
      token: "ac80cdb0-2ca6-4182-ae14-15158c33c095"
    exposedByDefault: false
    prefix: "traefik"
    refreshInterval: "15s"

log:
  level: DEBUG
  format: common

entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"
  postgresql:
    address: ":5432"
