
services:
  notebookum:
    container_name: notebookum
    build:
      context: ../../
      dockerfile: Dockerfile
    image: notebookum:1.0.0
    ports:
      - "8000:8000"
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY:-default}
      OPENAI_MODEL: ${OPENAI_MODEL:-gpt-4}
      DATABASE_URL: ${DATABASE_URL:-postgresql+psycopg://defaultuser:defaultpassword@postgresql-servidor:5432/defaultdb}
    networks:
      - notebookum-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.notebookum=true"
      - "traefik.http.routers.notebookum.rule=Host(`notebookum.local`)"
      - "traefik.http.routers.notebookum.tls=true"
      - "traefik.http.services.notebookum.loadbalancer.server.port=8000"

networks:
  notebookum-network:
    external: true